[package]
name = "ripley-core"
version.workspace = true
edition.workspace = true

[dependencies]
notify = { workspace = true }
redb = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
