[package]
name = "ripley-guard"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "ripley"

[[bin]]
name = "ripley"
path = "src/main.rs"

[[bin]]
name = "ripley-npm-shim"
path = "src/bin/ripley-npm-shim.rs"

[[bin]]
name = "ripley-pnpm-shim"
path = "src/bin/ripley-pnpm-shim.rs"

[[bin]]
name = "ripley-yarn-shim"
path = "src/bin/ripley-yarn-shim.rs"

[[bin]]
name = "ripley-pip-shim"
path = "src/bin/ripley-pip-shim.rs"

[[bin]]
name = "ripley-cargo-shim"
path = "src/bin/ripley-cargo-shim.rs"

[[bin]]
name = "ripley-go-shim"
path = "src/bin/ripley-go-shim.rs"

[[bin]]
name = "ripley-gem-shim"
path = "src/bin/ripley-gem-shim.rs"

[[bin]]
name = "ripley-script-shell"
path = "src/bin/ripley-script-shell.rs"

[dependencies]
ripley-core = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
ripley-ipc = { workspace = true }
tokio-util = { workspace = true }
notify = { workspace = true }
notify-rust = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
