// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async ping(): Promise<string> {
    return await TAURI_INVOKE("ping");
  },
  async submitGuardDecision(id: string, decision: Decision): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("submit_guard_decision", { id, decision }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async reportVisible(id: string): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("report_visible", { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listAlerts(projectPath: string): Promise<Result<AlertSummary[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_alerts", { projectPath }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listGuardLog(offset: number, limit: number): Promise<Result<GuardLogPage, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_guard_log", { offset, limit }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async runDeepScan(projectPath: string): Promise<Result<DeepScanReportDto, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("run_deep_scan", { projectPath }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listMonitorEvents(limit: number): Promise<Result<MonitorEntryDto[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_monitor_events", { limit }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async runAuditReport(): Promise<Result<AuditReportDto, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("run_audit_report") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async runHardenReport(projectPath: string): Promise<Result<HardenReportDto, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("run_harden_report", { projectPath }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  guardEvent: GuardEvent;
}>({
  guardEvent: "guard-event",
});

/** user-defined constants **/

/** user-defined types **/

export type AlertSummary = {
  id: string;
  advisory_id: string;
  ecosystem: string;
  package: string;
  version: string;
  severity: string;
  summary: string;
  references: string[];
  project_path: string;
};
export type AuditFindingDto = {
  name: string;
  status: string;
  detail: string;
  fix_command: string | null;
};
export type AuditReportDto = { categories: CategoryReportDto[]; timestamp: string };
export type CategoryReportDto = { category: string; findings: AuditFindingDto[]; overall: string };
export type Decision = "Allow" | "Block" | "Trust";
export type DeepScanReportDto = {
  project_path: string;
  ioc_count: number;
  persistence_count: number;
  credential_count: number;
  findings: ForensicFindingDto[];
  dead_man_switch_warning: string | null;
};
export type DetectedPmDto = {
  name: string;
  version: string | null;
  lockfile_path: string;
  binary: boolean;
};
export type ForensicFindingDto = {
  kind: string;
  path: string;
  description: string;
  severity: string;
  profile_id: string | null;
  rotation_command: string | null;
};
export type GuardEvent = GuardEventPayload;
export type GuardEventPayload = {
  id: string;
  package: string;
  version: string;
  script: string;
  risk_level: string;
  matched_rules: string[];
};
export type GuardLogEntry = {
  timestamp: string;
  package: string;
  version: string;
  script: string;
  action: string;
  risk_level: string;
  matched_rules: string[];
  source: string;
  user_decision: boolean | null;
};
export type GuardLogPage = { entries: GuardLogEntry[]; total: number };
export type HardenCategoryReportDto = {
  category: string;
  findings: HardenFindingDto[];
  overall: string;
};
export type HardenFindingDto = {
  name: string;
  status: string;
  detail: string;
  fix_command: string | null;
  pm: string;
};
export type HardenReportDto = {
  detected_pms: DetectedPmDto[];
  categories: HardenCategoryReportDto[];
  timestamp: string;
};
export type MonitorEntryDto = {
  timestamp: string;
  event_type: string;
  severity: string;
  process: string;
  pid: number | null;
  reason: string;
  detail: string;
  action: string;
};

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: "ok"; data: T } | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
